// marketplace-frontend/src/app/components/requirement-form/requirement-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { Requirement } from '../../models/models';

@Component({
  selector: 'app-requirement-form',
  templateUrl: './requirement-form.component.html',
  styleUrls: ['./requirement-form.component.css']
})
export class RequirementFormComponent implements OnInit {
  isEdit = false;
  reqId?: number;
  loading = false;
  submitting = false;
  errorMsg = '';

  title = '';
  description = '';
  category = '';
  type = '';
  price = 0;

  categories = ['Accommodation', 'Electronics', 'Vehicle', 'Services', 'Other'];
  types = ['SELL', 'RENT', 'FREE', 'HELP'];

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private api: ApiService,
    private auth: AuthService
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id && id !== 'new') {
      this.isEdit = true;
      this.reqId = Number(id);
      this.loading = true;
      this.api.getRequirement(this.reqId).subscribe({
        next: (req) => {
          this.title = req.title;
          this.description = req.description || '';
          this.category = req.category || '';
          this.type = req.type || '';
          this.price = req.price || 0;
          this.loading = false;
        },
        error: () => this.router.navigate(['/requirements'])
      });
    }
  }

  onSubmit(): void {
    if (!this.title || !this.category) {
      this.errorMsg = 'Title and category are required.';
      return;
    }
    this.submitting = true;
    this.errorMsg = '';

    const emp = this.auth.currentEmployee!;
    const req: Requirement = {
      resId: this.reqId,
      title: this.title,
      description: this.description,
      category: this.category,
      type: this.type,
      price: this.price,
      emp
    };

    const call = this.isEdit ? this.api.updateRequirement(req) : this.api.addRequirement(req);
    call.subscribe({
      next: () => {
        this.submitting = false;
        this.router.navigate(['/dashboard']);
      },
      error: (err) => {
        this.submitting = false;
        this.errorMsg = err?.error?.message || 'Failed to save requirement.';
      }
    });
  }
}

<div class="page-content">
  <div class="container">
    <div class="form-page animate-fade-in">
      <div class="form-header">
        <a routerLink="/dashboard" class="back-link">← Back</a>
        <h1>{{ isEdit ? '✏️ Edit Requirement' : '📋 Post a Requirement' }}</h1>
        <p class="text-muted">{{ isEdit ? 'Update your requirement details' : 'Tell others what you need' }}</p>
      </div>

      <div *ngIf="loading" class="spinner"></div>

      <div class="card form-card" *ngIf="!loading">
        <div class="alert alert-danger" *ngIf="errorMsg">⚠️ {{ errorMsg }}</div>

        <form (ngSubmit)="onSubmit()" id="req-form">
          <div class="form-group">
            <label class="form-label" for="req-title">Title *</label>
            <input id="req-title" type="text" class="form-control"
                   placeholder="e.g. Looking for PG accommodation near Koramangala"
                   [(ngModel)]="title" name="title" required />
          </div>

          <div class="form-group">
            <label class="form-label" for="req-desc">Description</label>
            <textarea id="req-desc" class="form-control" rows="4"
                      placeholder="Provide more details about your requirement..."
                      [(ngModel)]="description" name="description"></textarea>
          </div>

          <div class="grid-2">
            <div class="form-group">
              <label class="form-label" for="req-category">Category *</label>
              <select id="req-category" class="form-control" [(ngModel)]="category" name="category" required>
                <option value="">Select category</option>
                <option *ngFor="let cat of categories" [value]="cat">{{ cat }}</option>
              </select>
            </div>
            <div class="form-group">
              <label class="form-label" for="req-type">Type</label>
              <select id="req-type" class="form-control" [(ngModel)]="type" name="type">
                <option value="">Select type</option>
                <option *ngFor="let t of types" [value]="t">{{ t }}</option>
              </select>
            </div>
          </div>

          <div class="form-group">
            <label class="form-label" for="req-price">Budget (₹)</label>
            <input id="req-price" type="number" class="form-control"
                   placeholder="0 for negotiable" [(ngModel)]="price" name="price" min="0" />
          </div>

          <div class="form-actions">
            <a routerLink="/dashboard" class="btn btn-outline">Cancel</a>
            <button id="req-submit" type="submit" class="btn btn-primary" [disabled]="submitting">
              <span *ngIf="submitting">⏳ Saving...</span>
              <span *ngIf="!submitting && !isEdit">📋 Post Requirement</span>
              <span *ngIf="!submitting && isEdit">✅ Update Requirement</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

// marketplace-react/src/components/RequirementForm/RequirementForm.jsx
import { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { getRequirement, addRequirement, updateRequirement } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { ArrowLeft, Save } from 'lucide-react';
import Spinner from '../shared/Spinner';

const CATEGORIES = ['Accommodation', 'Electronics', 'Vehicle', 'Services', 'Other'];
const TYPES = ['SELL', 'RENT', 'FREE', 'HELP'];

const RequirementForm = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { state } = useAuth();
  
  const isEdit = !!id;
  const [loading, setLoading] = useState(isEdit);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    category: '',
    type: '',
    price: ''
  });

  const fetchReq = useCallback(async () => {
    try {
      const res = await getRequirement(id);
      const req = res.data;
      if (req.emp?.empId !== state.employee?.empId) {
        navigate('/dashboard'); // Not owner
        return;
      }
      setFormData({
        title: req.title || '',
        description: req.description || '',
        category: req.category || '',
        type: req.type || '',
        price: req.price || ''
      });
    } catch (err) {
      console.error(err);
      setError('Failed to load requirement.');
    } finally {
      setLoading(false);
    }
  }, [id, navigate, state.employee?.empId]);

  useEffect(() => {
    if (isEdit) fetchReq();
  }, [isEdit, fetchReq]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    setError('');

    const payload = {
      ...formData,
      price: formData.price ? Number(formData.price) : 0,
      emp: { empId: state.employee.empId }
    };

    try {
      if (isEdit) {
        await updateRequirement({ ...payload, resId: Number(id) });
      } else {
        await addRequirement({ ...payload, date: new Date().toISOString().split('T')[0] });
      }
      navigate('/dashboard');
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to save requirement.');
      setSubmitting(false);
    }
  };

  return (
    <div className="page-content">
      <div className="container" style={{ maxWidth: '700px' }}>
        
        <div className="mb-6 animate-fade-in">
          <Link to="/dashboard" className="back-link">
            <ArrowLeft size={16} /> Back
          </Link>
          <h1 className="text-2xl mb-2">{isEdit ? '✏️ Edit Requirement' : '📋 Post a Requirement'}</h1>
          <p className="text-secondary">
            {isEdit ? 'Update your requirement details' : 'Tell others what you need'}
          </p>
        </div>

        {loading ? (
          <Spinner />
        ) : (
          <div className="card animate-slide-up">
            {error && <div className="alert alert-danger">{error}</div>}

            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label className="form-label" htmlFor="title">Title *</label>
                <input 
                  id="title" name="title" type="text" className="form-control"
                  placeholder="e.g. Looking for PG accommodation near office"
                  value={formData.title} onChange={handleChange} required 
                />
              </div>

              <div className="form-group">
                <label className="form-label" htmlFor="description">Description</label>
                <textarea 
                  id="description" name="description" className="form-control" rows="4"
                  placeholder="Provide more details..."
                  value={formData.description} onChange={handleChange} 
                />
              </div>

              <div className="grid-2">
                <div className="form-group">
                  <label className="form-label" htmlFor="category">Category *</label>
                  <select id="category" name="category" className="form-control" 
                          value={formData.category} onChange={handleChange} required>
                    <option value="">Select category</option>
                    {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label" htmlFor="type">Type</label>
                  <select id="type" name="type" className="form-control" 
                          value={formData.type} onChange={handleChange}>
                    <option value="">Select type</option>
                    {TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                  </select>
                </div>
              </div>

              <div className="form-group">
                <label className="form-label" htmlFor="price">Budget (₹)</label>
                <input 
                  id="price" name="price" type="number" className="form-control"
                  placeholder="0 for negotiable" min="0"
                  value={formData.price} onChange={handleChange} 
                />
              </div>

              <div className="flex gap-4 mt-8">
                <button type="submit" className="btn btn-primary flex-1 justify-center" disabled={submitting}>
                  {submitting ? 'Saving...' : <><Save size={16} /> {isEdit ? 'Update Requirement' : 'Post Requirement'}</>}
                </button>
                <Link to="/dashboard" className="btn btn-outline flex-1 justify-center text-center">
                  Cancel
                </Link>
              </div>
            </form>
          </div>
        )}
      </div>
    </div>
  );
};

export default RequirementForm;
