// marketplace-react/src/components/Login/Login.jsx
import { useState } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { getEmployeeByUserId } from '../../services/api';
import { LogIn, Eye, EyeOff, AlertCircle } from 'lucide-react';
import styles from './Login.module.css';

const Login = () => {
  const { login, setSession } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const from = location.state?.from?.pathname || '/marketplace';

  const [userId, setUserId]     = useState('');
  const [password, setPassword] = useState('');
  const [showPass, setShowPass] = useState(false);
  const [loading, setLoading]   = useState(false);
  const [error, setError]       = useState('');

  const onSubmit = async (e) => {
    e.preventDefault();
    if (!userId.trim() || !password.trim()) {
      setError('Please enter your Employee ID and password.');
      return;
    }
    setLoading(true);
    setError('');
    try {
      const user = await login(userId.trim(), password);
      // Fetch linked employee
      let employee = null;
      try {
        const empRes = await getEmployeeByUserId(userId.trim());
        employee = empRes.data;
      } catch { /* no employee yet */ }
      setSession(user, employee);
      navigate(from, { replace: true });
    } catch (err) {
      setError(err.response?.data?.message || 'Invalid credentials. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.page}>
      {/* Background orbs */}
      <div className={styles.orb1} />
      <div className={styles.orb2} />

      <div className={`${styles.card} animate-fade-in`}>
        <div className={styles.header}>
          <div className={styles.logo}>🏪</div>
          <h1>Welcome Back</h1>
          <p className="text-secondary">Sign in to your InHouseMarket account</p>
        </div>

        {error && (
          <div className="alert alert-danger">
            <AlertCircle size={16} /> {error}
          </div>
        )}

        <form id="login-form" onSubmit={onSubmit}>
          <div className="form-group">
            <label className="form-label" htmlFor="login-userId">Employee ID / Email</label>
            <input
              id="login-userId"
              type="text"
              className="form-control"
              placeholder="e.g. emp001@company.com"
              value={userId}
              onChange={e => setUserId(e.target.value)}
              autoComplete="username"
              required
            />
          </div>

          <div className="form-group">
            <label className="form-label" htmlFor="login-password">Password</label>
            <div className={styles.passWrapper}>
              <input
                id="login-password"
                type={showPass ? 'text' : 'password'}
                className="form-control"
                placeholder="Enter your password"
                value={password}
                onChange={e => setPassword(e.target.value)}
                autoComplete="current-password"
                required
              />
              <button
                type="button"
                className={styles.eyeBtn}
                onClick={() => setShowPass(!showPass)}
                tabIndex={-1}
                aria-label="Toggle password visibility"
              >
                {showPass ? <EyeOff size={16} /> : <Eye size={16} />}
              </button>
            </div>
          </div>

          <button
            id="login-submit"
            type="submit"
            className="btn btn-primary w-full btn-lg"
            disabled={loading}
          >
            {loading ? (
              <><span className={styles.spinnerInline} /> Signing in...</>
            ) : (
              <><LogIn size={17} /> Sign In</>
            )}
          </button>
        </form>

        <div className={styles.footer}>
          <p>Don&apos;t have an account?{' '}
            <Link to="/register">Register here</Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;

// marketplace-frontend/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ApiService } from '../../services/api.service';
import { User, Employee } from '../../models/models';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  userId = '';
  password = '';
  loading = false;
  errorMsg = '';

  constructor(
    private auth: AuthService,
    private api: ApiService,
    private router: Router
  ) {}

  onSubmit(): void {
    if (!this.userId || !this.password) {
      this.errorMsg = 'Please fill in all fields.';
      return;
    }
    this.loading = true;
    this.errorMsg = '';

    const user: User = { userId: this.userId, password: this.password };

    this.auth.login(user).subscribe({
      next: (loggedInUser) => {
        // Resolve the real Employee profile linked to this user
        this.api.getEmployeeByUserId(loggedInUser.userId).subscribe({
          next: (emp) => {
            this.auth.setSession(loggedInUser, emp);
            this.router.navigate(['/dashboard']);
          },
          error: () => {
            // No employee profile yet — create one so empId is always populated
            const newEmp: Employee = { empName: loggedInUser.userId, user: loggedInUser };
            this.api.addEmployee(newEmp).subscribe({
              next: (savedEmp) => {
                this.auth.setSession(loggedInUser, savedEmp);
                this.router.navigate(['/dashboard']);
              },
              error: () => {
                this.loading = false;
                this.errorMsg = 'Logged in, but could not load your employee profile.';
              }
            });
          }
        });
      },
      error: (err) => {
        this.loading = false;
        this.errorMsg = err?.error?.message || 'Invalid credentials. Please try again.';
      }
    });
  }
}

<div class="auth-page">
  <div class="auth-card animate-fade-in">
    <!-- Header -->
    <div class="auth-header">
      <div class="auth-logo">🏪</div>
      <h1>Welcome Back</h1>
      <p>Sign in to your InHouse Marketplace account</p>
    </div>

    <!-- Error alert -->
    <div class="alert alert-danger" *ngIf="errorMsg">
      ⚠️ {{ errorMsg }}
    </div>

    <!-- Form -->
    <form (ngSubmit)="onSubmit()" id="login-form">
      <div class="form-group">
        <label class="form-label" for="login-userId">Employee ID / Email</label>
        <input
          id="login-userId"
          type="text"
          class="form-control"
          placeholder="e.g. emp001@company.com"
          [(ngModel)]="userId"
          name="userId"
          autocomplete="username"
          required
        />
      </div>

      <div class="form-group">
        <label class="form-label" for="login-password">Password</label>
        <input
          id="login-password"
          type="password"
          class="form-control"
          placeholder="Enter your password"
          [(ngModel)]="password"
          name="password"
          autocomplete="current-password"
          required
        />
      </div>

      <button
        id="login-submit"
        type="submit"
        class="btn btn-primary w-full btn-lg"
        [disabled]="loading"
      >
        <span *ngIf="loading">⏳ Signing in...</span>
        <span *ngIf="!loading">🚀 Sign In</span>
      </button>
    </form>

    <div class="auth-footer">
      <p>Don't have an account? <a routerLink="/register">Register here</a></p>
    </div>
  </div>

  <!-- Background decoration -->
  <div class="auth-bg-decoration">
    <div class="orb orb-1"></div>
    <div class="orb orb-2"></div>
  </div>
</div>
