// marketplace-frontend/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService, AuthState } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  authState!: AuthState;
  menuOpen = false;

  constructor(private auth: AuthService, private router: Router) {}

  ngOnInit(): void {
    this.auth.state.subscribe(state => (this.authState = state));
  }

  logout(): void {
    this.auth.logout();
    this.router.navigate(['/login']);
  }

  toggleMenu(): void {
    this.menuOpen = !this.menuOpen;
  }

  closeMenu(): void {
    this.menuOpen = false;
  }
}

<nav class="navbar">
  <div class="nav-container">
    <!-- Logo -->
    <a class="nav-brand" routerLink="/" (click)="closeMenu()">
      <span class="brand-icon">🏪</span>
      <span class="brand-name">InHouse<span class="brand-accent">Market</span></span>
    </a>

    <!-- Desktop Links -->
    <ul class="nav-links" [class.open]="menuOpen">
      <li><a routerLink="/marketplace" routerLinkActive="active" (click)="closeMenu()">🔍 Browse</a></li>
      <li><a routerLink="/requirements" routerLinkActive="active" (click)="closeMenu()">📋 Requirements</a></li>
      <li><a routerLink="/offers" routerLinkActive="active" (click)="closeMenu()">📦 Offers</a></li>
      <li *ngIf="authState?.isLoggedIn">
        <a routerLink="/dashboard" routerLinkActive="active" (click)="closeMenu()">👤 Dashboard</a>
      </li>
    </ul>

    <!-- Auth section -->
    <div class="nav-auth">
      <ng-container *ngIf="authState?.isLoggedIn; else notLoggedIn">
        <span class="nav-user">Hi, {{ authState.employee?.empName || authState.user?.userId }}</span>
        <button class="btn btn-outline btn-sm" (click)="logout()">Logout</button>
      </ng-container>
      <ng-template #notLoggedIn>
        <a routerLink="/login" class="btn btn-outline btn-sm" (click)="closeMenu()">Login</a>
        <a routerLink="/register" class="btn btn-primary btn-sm" (click)="closeMenu()">Register</a>
      </ng-template>
    </div>

    <!-- Hamburger -->
    <button class="hamburger" (click)="toggleMenu()" [attr.aria-label]="menuOpen ? 'Close menu' : 'Open menu'">
      <span></span><span></span><span></span>
    </button>
  </div>
</nav>

// marketplace-react/src/components/Navbar/Navbar.jsx
import { useState, useEffect } from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { ShoppingBag, LayoutDashboard, LogOut, LogIn, UserPlus, Menu, X, ChevronRight } from 'lucide-react';
import styles from './Navbar.module.css';

const Navbar = () => {
  const { state, logout } = useAuth();
  const navigate = useNavigate();
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const handleLogout = () => {
    logout();
    navigate('/marketplace');
    setMenuOpen(false);
  };

  const closeMenu = () => setMenuOpen(false);

  return (
    <nav className={`${styles.navbar} ${scrolled ? styles.scrolled : ''}`}>
      <div className={styles.container}>
        {/* Brand */}
        <Link to="/marketplace" className={styles.brand} onClick={closeMenu}>
          <span className={styles.brandIcon}>🏪</span>
          <span className={styles.brandName}>
            InHouse<span className={styles.brandAccent}>Market</span>
          </span>
        </Link>

        {/* Desktop Links */}
        <ul className={`${styles.links} ${menuOpen ? styles.open : ''}`}>
          <li>
            <NavLink to="/marketplace" className={({ isActive }) => isActive ? styles.active : ''} onClick={closeMenu}>
              🔍 Browse
            </NavLink>
          </li>
          <li>
            <NavLink to="/requirements" className={({ isActive }) => isActive ? styles.active : ''} onClick={closeMenu}>
              📋 Requirements
            </NavLink>
          </li>
          <li>
            <NavLink to="/offers" className={({ isActive }) => isActive ? styles.active : ''} onClick={closeMenu}>
              📦 Offers
            </NavLink>
          </li>
          {state.isLoggedIn && (
            <li>
              <NavLink to="/dashboard" className={({ isActive }) => isActive ? styles.active : ''} onClick={closeMenu}>
                <LayoutDashboard size={15} style={{ verticalAlign: 'middle' }} /> Dashboard
              </NavLink>
            </li>
          )}
        </ul>

        {/* Auth section */}
        <div className={styles.auth}>
          {state.isLoggedIn ? (
            <>
              <span className={styles.userName}>
                Hi, {state.employee?.empName || state.user?.userId}
              </span>
              <button className="btn btn-outline btn-sm" onClick={handleLogout}>
                <LogOut size={14} /> Logout
              </button>
            </>
          ) : (
            <>
              <Link to="/login" className="btn btn-outline btn-sm" onClick={closeMenu}>
                <LogIn size={14} /> Login
              </Link>
              <Link to="/register" className="btn btn-primary btn-sm" onClick={closeMenu}>
                <UserPlus size={14} /> Register
              </Link>
            </>
          )}
        </div>

        {/* Hamburger */}
        <button
          className={styles.hamburger}
          onClick={() => setMenuOpen(!menuOpen)}
          aria-label={menuOpen ? 'Close menu' : 'Open menu'}
        >
          {menuOpen ? <X size={22} /> : <Menu size={22} />}
        </button>
      </div>
    </nav>
  );
};

export default Navbar;
