// marketplace-react/src/components/OfferDetail/OfferDetail.jsx
import { useState, useEffect, useCallback } from 'react';
import { useParams, Link } from 'react-router-dom';
import { getOffer, addProposal } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { ArrowLeft, CheckCircle, XCircle, Send } from 'lucide-react';
import Spinner from '../shared/Spinner';
import Badge from '../shared/Badge';
import EmptyState from '../shared/EmptyState';

const OfferDetail = () => {
  const { id } = useParams();
  const { state } = useAuth();
  const [offer, setOffer] = useState(null);
  const [loading, setLoading] = useState(true);
  
  // Proposal Form
  const [proposalText, setProposalText] = useState('');
  const [proposalAmount, setProposalAmount] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [msg, setMsg] = useState({ type: '', text: '' });

  const fetchOffer = useCallback(async () => {
    try {
      const res = await getOffer(id);
      setOffer(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    fetchOffer();
  }, [fetchOffer]);

  const handleSubmitProposal = async (e) => {
    e.preventDefault();
    if (!proposalText.trim()) return;
    
    setSubmitting(true);
    setMsg({ type: '', text: '' });
    
    try {
      await addProposal({
        proposal: proposalText,
        amount: proposalAmount || 0,
        emp: { empId: state.employee.empId },
        resource: { resId: offer.resId }
      });
      setMsg({ type: 'success', text: 'Proposal submitted successfully!' });
      setProposalText('');
      setProposalAmount('');
    } catch (err) {
      setMsg({ type: 'error', text: 'Failed to submit proposal.' });
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return <div className="page-content"><Spinner /></div>;
  if (!offer) return <div className="page-content"><EmptyState icon="😕" message="Offer not found" /></div>;

  const isOwner = state.employee?.empId === offer.emp?.empId;

  return (
    <div className="page-content">
      <div className="container">
        <Link to="/marketplace" className="back-link animate-fade-in">
          <ArrowLeft size={16} /> Back to Marketplace
        </Link>

        <div className="grid-2 animate-slide-up">
          {/* Main Info */}
          <div className="card h-full">
            <div className="flex gap-2 mb-4 flex-wrap">
              <Badge variant="primary">{offer.category}</Badge>
              <Badge variant="warning">{offer.type}</Badge>
              {offer.available 
                ? <Badge variant="success"><CheckCircle size={12} className="mr-1"/> Available</Badge>
                : <Badge variant="danger"><XCircle size={12} className="mr-1"/> Unavailable</Badge>
              }
            </div>
            
            <h1 className="mb-4 text-2xl">{offer.title}</h1>
            <p className="text-secondary mb-6 whitespace-pre-line">{offer.description}</p>
            
            <div className="grid-2 gap-4 mt-auto border-t border-gray-700 pt-6">
              {offer.price > 0 && (
                <div>
                  <div className="text-sm text-muted uppercase tracking-wider mb-1">Price</div>
                  <div className="text-warning font-bold text-xl">₹{offer.price.toLocaleString()}</div>
                </div>
              )}
              <div>
                <div className="text-sm text-muted uppercase tracking-wider mb-1">Offered By</div>
                <div className="font-medium">{offer.emp?.empName}</div>
              </div>
              <div>
                <div className="text-sm text-muted uppercase tracking-wider mb-1">Department</div>
                <div>{offer.emp?.deptName || '—'}</div>
              </div>
              <div>
                <div className="text-sm text-muted uppercase tracking-wider mb-1">Location</div>
                <div>{offer.emp?.location || '—'}</div>
              </div>
              <div>
                <div className="text-sm text-muted uppercase tracking-wider mb-1">Posted On</div>
                <div>{offer.date ? new Date(offer.date).toLocaleDateString() : '—'}</div>
              </div>
              {offer.availableUpto && (
                <div>
                  <div className="text-sm text-muted uppercase tracking-wider mb-1">Available Until</div>
                  <div>{new Date(offer.availableUpto).toLocaleDateString()}</div>
                </div>
              )}
            </div>
          </div>

          {/* Proposal Panel */}
          <div className="card">
            <h2 className="mb-2 flex items-center gap-2">🤝 {isOwner ? 'Proposals Received' : 'Make an Offer'}</h2>
            
            {!state.isLoggedIn ? (
              <div className="empty-state py-8">
                <div className="icon mb-4">🔐</div>
                <p>Please <Link to="/login" className="text-primary-light font-bold">login</Link> to submit a proposal.</p>
              </div>
            ) : isOwner ? (
              <div className="mt-6">
                {offer.proposals?.length === 0 ? (
                  <EmptyState icon="📬" message="No proposals received yet." />
                ) : (
                  <div className="flex flex-col gap-4">
                    {offer.proposals?.map(p => (
                      <div key={p.propId} className="p-4 rounded-lg bg-black/20 border border-gray-700">
                        <div className="flex justify-between items-start mb-2">
                          <span className="font-semibold text-primary-light">{p.emp?.empName}</span>
                          <span className="font-mono text-warning">₹{p.amount.toLocaleString()}</span>
                        </div>
                        <p className="text-sm text-secondary">{p.proposal}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ) : !offer.available ? (
               <div className="empty-state py-8">
                 <XCircle size={48} className="mx-auto mb-4 text-danger opacity-50" />
                 <p>This offer is no longer available.</p>
               </div>
            ) : (
              <div className="mt-6">
                <p className="text-muted text-sm mb-6">Interested in this offer? Submit a proposal to the owner.</p>
                
                {msg.text && (
                  <div className={`alert ${msg.type === 'success' ? 'alert-success' : 'alert-danger'}`}>
                    {msg.text}
                  </div>
                )}

                <form onSubmit={handleSubmitProposal}>
                  <div className="form-group">
                    <label className="form-label" htmlFor="propText">Your Proposal *</label>
                    <textarea 
                      id="propText" 
                      className="form-control" 
                      rows="4" 
                      placeholder="Tell the seller what you'd like..."
                      value={proposalText}
                      onChange={e => setProposalText(e.target.value)}
                      required
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-label" htmlFor="propAmt">Your Offer Amount (₹)</label>
                    <input 
                      id="propAmt" 
                      type="number" 
                      className="form-control" 
                      placeholder="0"
                      value={proposalAmount}
                      onChange={e => setProposalAmount(e.target.value)}
                      min="0"
                    />
                  </div>
                  <button type="submit" className="btn btn-accent w-full" disabled={submitting}>
                    {submitting ? <Spinner /> : <><Send size={16} /> Submit Proposal</>}
                  </button>
                </form>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default OfferDetail;

// marketplace-frontend/src/app/components/offer-detail/offer-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { Offer, Proposal } from '../../models/models';

@Component({
  selector: 'app-offer-detail',
  templateUrl: './offer-detail.component.html',
  styleUrls: ['./offer-detail.component.css']
})
export class OfferDetailComponent implements OnInit {
  offer!: Offer;
  loading = true;
  proposalText = '';
  proposalAmount = 0;
  submitting = false;
  successMsg = '';
  errorMsg = '';

  get isLoggedIn() { return this.auth.isLoggedIn; }
  get currentEmp() { return this.auth.currentEmployee; }

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private api: ApiService,
    private auth: AuthService
  ) {}

  ngOnInit(): void {
    const id = Number(this.route.snapshot.paramMap.get('id'));
    this.api.getOffer(id).subscribe({
      next: (offer) => { this.offer = offer; this.loading = false; },
      error: () => { this.loading = false; this.router.navigate(['/offers']); }
    });
  }

  submitProposal(): void {
    if (!this.proposalText) { this.errorMsg = 'Proposal text is required.'; return; }
    this.submitting = true;
    this.errorMsg = '';

    const prop: Proposal = {
      proposal: this.proposalText,
      amount: this.proposalAmount,
      emp: this.currentEmp!,
      resource: { resId: this.offer.resId } as any
    };

    this.api.addProposal(prop).subscribe({
      next: () => {
        this.submitting = false;
        this.successMsg = '🎉 Proposal submitted!';
        this.proposalText = '';
        this.proposalAmount = 0;
      },
      error: (err) => {
        this.submitting = false;
        this.errorMsg = err?.error?.message || 'Failed to submit proposal.';
      }
    });
  }
}

<div class="page-content">
  <div class="container">
    <div *ngIf="loading" class="spinner"></div>

    <ng-container *ngIf="!loading && offer">
      <a routerLink="/marketplace" class="back-link">← Back to Marketplace</a>

      <div class="detail-layout animate-fade-in">
        <div class="detail-main card">
          <div class="detail-tags">
            <span class="badge badge-primary">{{ offer.category }}</span>
            <span class="badge badge-warning">{{ offer.type }}</span>
            <span class="badge badge-success" *ngIf="offer.available">🟢 Available</span>
            <span class="badge badge-danger" *ngIf="!offer.available">🔴 Unavailable</span>
          </div>
          <h1 class="detail-title">{{ offer.title }}</h1>
          <p class="detail-desc">{{ offer.description }}</p>

          <div class="detail-meta">
            <div class="meta-item" *ngIf="offer.price">
              <span class="meta-label">Price</span>
              <span class="meta-value price">₹{{ offer.price | number }}</span>
            </div>
            <div class="meta-item">
              <span class="meta-label">Offered by</span>
              <span class="meta-value">{{ offer.emp?.empName }}</span>
            </div>
            <div class="meta-item">
              <span class="meta-label">Department</span>
              <span class="meta-value">{{ offer.emp?.deptName || '—' }}</span>
            </div>
            <div class="meta-item">
              <span class="meta-label">Location</span>
              <span class="meta-value">{{ offer.emp?.location || '—' }}</span>
            </div>
            <div class="meta-item" *ngIf="offer.date">
              <span class="meta-label">Posted on</span>
              <span class="meta-value">{{ offer.date | date }}</span>
            </div>
            <div class="meta-item" *ngIf="offer.availableUpto">
              <span class="meta-label">Available until</span>
              <span class="meta-value">{{ offer.availableUpto | date }}</span>
            </div>
          </div>
        </div>

        <!-- Proposal panel -->
        <div class="proposal-panel card" *ngIf="isLoggedIn && offer.available">
          <h2>🤝 Make a Proposal</h2>
          <p class="text-muted text-sm">Interested in this offer? Submit a proposal.</p>

          <div class="alert alert-success" *ngIf="successMsg">{{ successMsg }}</div>
          <div class="alert alert-danger" *ngIf="errorMsg">{{ errorMsg }}</div>

          <form (ngSubmit)="submitProposal()" id="offer-proposal-form">
            <div class="form-group">
              <label class="form-label" for="offer-prop-text">Your Proposal</label>
              <textarea id="offer-prop-text" class="form-control" rows="4"
                        placeholder="Tell the seller what you'd like..."
                        [(ngModel)]="proposalText" name="proposalText" required></textarea>
            </div>
            <div class="form-group">
              <label class="form-label" for="offer-prop-amount">Your Offer Amount (₹)</label>
              <input id="offer-prop-amount" type="number" class="form-control"
                     placeholder="0" [(ngModel)]="proposalAmount" name="proposalAmount" min="0" />
            </div>
            <button id="btn-submit-offer-proposal" type="submit" class="btn btn-accent w-full"
                    [disabled]="submitting">
              <span *ngIf="submitting">⏳ Submitting...</span>
              <span *ngIf="!submitting">🚀 Submit Proposal</span>
            </button>
          </form>
        </div>

        <div class="proposal-panel card" *ngIf="!isLoggedIn">
          <div class="empty-state">
            <div class="icon">🔐</div>
            <p>Please <a routerLink="/login">login</a> to submit a proposal.</p>
          </div>
        </div>
      </div>
    </ng-container>
  </div>
</div>
