// marketplace-frontend/src/app/components/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { Requirement, Offer, Proposal, Employee } from '../../models/models';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  employee!: Employee;
  myRequirements: Requirement[] = [];
  myOffers: Offer[] = [];
  myProposals: Proposal[] = [];
  loading = true;
  activeTab: 'requirements' | 'offers' | 'proposals' = 'requirements';

  constructor(private api: ApiService, private auth: AuthService) {}

  ngOnInit(): void {
    const emp = this.auth.currentEmployee;
    if (emp?.empId) {
      this.employee = emp;
      this.loadData(emp.empId);
    } else {
      this.loading = false;
    }
  }

  loadData(empId: number): void {
    this.api.getEmployeeRequirements(empId).subscribe({
      next: (reqs) => { this.myRequirements = reqs; },
      error: () => {}
    });
    this.api.getEmployeeOffers(empId).subscribe({
      next: (offers) => { this.myOffers = offers; },
      error: () => {}
    });
    this.api.getAllProposals().subscribe({
      next: (props) => {
        this.myProposals = props.filter(p => p.emp?.empId === empId);
        this.loading = false;
      },
      error: () => { this.loading = false; }
    });
  }

  markFulfilled(req: Requirement): void {
    this.api.updateRequirementFulfilled(req).subscribe({
      next: (updated) => {
        const idx = this.myRequirements.findIndex(r => r.resId === updated.resId);
        if (idx > -1) this.myRequirements[idx] = updated;
      }
    });
  }

  markUnavailable(offer: Offer): void {
    const updated = { ...offer, available: false };
    this.api.updateOfferAvailability(updated).subscribe({
      next: (res) => {
        const idx = this.myOffers.findIndex(o => o.resId === res.resId);
        if (idx > -1) this.myOffers[idx] = res;
      }
    });
  }

  deleteRequirement(reqId: number): void {
    if (!confirm('Delete this requirement?')) return;
    this.api.deleteRequirement(reqId).subscribe({
      next: () => { this.myRequirements = this.myRequirements.filter(r => r.resId !== reqId); }
    });
  }

  deleteOffer(offerId: number): void {
    if (!confirm('Delete this offer?')) return;
    this.api.deleteOffer(offerId).subscribe({
      next: () => { this.myOffers = this.myOffers.filter(o => o.resId !== offerId); }
    });
  }

  deleteProposal(propId: number): void {
    if (!confirm('Delete this proposal?')) return;
    this.api.deleteProposal(propId).subscribe({
      next: () => { this.myProposals = this.myProposals.filter(p => p.propId !== propId); }
    });
  }
}

<div class="page-content">
  <div class="container">
    <!-- Header -->
    <div class="dashboard-header animate-fade-in">
      <div>
        <h1>My Dashboard</h1>
        <p class="text-muted">Manage your requirements, offers and proposals</p>
      </div>
      <div class="header-actions">
        <a routerLink="/requirements/new" class="btn btn-primary" id="btn-add-requirement">
          ➕ New Requirement
        </a>
        <a routerLink="/offers/new" class="btn btn-accent" id="btn-add-offer">
          🚀 New Offer
        </a>
      </div>
    </div>

    <!-- Spinner -->
    <div *ngIf="loading" class="spinner"></div>

    <ng-container *ngIf="!loading">
      <!-- Stats row -->
      <div class="stats-row animate-fade-in">
        <div class="stat-card" [class.active]="activeTab === 'requirements'" (click)="activeTab = 'requirements'">
          <div class="stat-icon">📋</div>
          <div class="stat-count">{{ myRequirements.length }}</div>
          <div class="stat-label">Requirements</div>
        </div>
        <div class="stat-card" [class.active]="activeTab === 'offers'" (click)="activeTab = 'offers'">
          <div class="stat-icon">📦</div>
          <div class="stat-count">{{ myOffers.length }}</div>
          <div class="stat-label">Offers</div>
        </div>
        <div class="stat-card" [class.active]="activeTab === 'proposals'" (click)="activeTab = 'proposals'">
          <div class="stat-icon">🤝</div>
          <div class="stat-count">{{ myProposals.length }}</div>
          <div class="stat-label">My Proposals</div>
        </div>
      </div>

      <!-- Requirements Tab -->
      <div *ngIf="activeTab === 'requirements'" class="tab-content animate-fade-in">
        <div class="empty-state" *ngIf="myRequirements.length === 0">
          <div class="icon">📋</div>
          <p>No requirements yet. Post your first requirement!</p>
          <a routerLink="/requirements/new" class="btn btn-primary">Post Requirement</a>
        </div>
        <div class="grid-auto" *ngIf="myRequirements.length > 0">
          <div class="resource-card card" *ngFor="let req of myRequirements">
            <div class="card-top">
              <span class="badge badge-primary">{{ req.category }}</span>
              <span class="badge badge-success" *ngIf="req.fulfilled">✅ Fulfilled</span>
              <span class="badge badge-warning" *ngIf="!req.fulfilled">⏳ Open</span>
            </div>
            <h3 class="card-title">{{ req.title }}</h3>
            <p class="card-desc text-muted text-sm">{{ req.description }}</p>
            <div class="card-meta">
              <span>{{ req.type }}</span>
              <span *ngIf="req.price">₹{{ req.price | number }}</span>
            </div>
            <div class="card-actions">
              <button *ngIf="!req.fulfilled" class="btn btn-success btn-sm"
                      (click)="markFulfilled(req)" [id]="'btn-fulfill-' + req.resId">
                ✅ Mark Fulfilled
              </button>
              <a [routerLink]="['/requirements', req.resId, 'edit']" class="btn btn-outline btn-sm">✏️ Edit</a>
              <button class="btn btn-danger btn-sm"
                      (click)="deleteRequirement(req.resId!)" [id]="'btn-del-req-' + req.resId">
                🗑️
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Offers Tab -->
      <div *ngIf="activeTab === 'offers'" class="tab-content animate-fade-in">
        <div class="empty-state" *ngIf="myOffers.length === 0">
          <div class="icon">📦</div>
          <p>No offers yet. Post your first offer!</p>
          <a routerLink="/offers/new" class="btn btn-accent">Post Offer</a>
        </div>
        <div class="grid-auto" *ngIf="myOffers.length > 0">
          <div class="resource-card card" *ngFor="let offer of myOffers">
            <div class="card-top">
              <span class="badge badge-primary">{{ offer.category }}</span>
              <span class="badge badge-success" *ngIf="offer.available">🟢 Available</span>
              <span class="badge badge-danger" *ngIf="!offer.available">🔴 Unavailable</span>
            </div>
            <h3 class="card-title">{{ offer.title }}</h3>
            <p class="card-desc text-muted text-sm">{{ offer.description }}</p>
            <div class="card-meta">
              <span>{{ offer.type }}</span>
              <span *ngIf="offer.price">₹{{ offer.price | number }}</span>
            </div>
            <div class="card-actions">
              <button *ngIf="offer.available" class="btn btn-outline btn-sm"
                      (click)="markUnavailable(offer)" [id]="'btn-unavail-' + offer.resId">
                🔴 Mark Unavailable
              </button>
              <a [routerLink]="['/offers', offer.resId, 'edit']" class="btn btn-outline btn-sm">✏️ Edit</a>
              <button class="btn btn-danger btn-sm"
                      (click)="deleteOffer(offer.resId!)" [id]="'btn-del-offer-' + offer.resId">
                🗑️
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Proposals Tab -->
      <div *ngIf="activeTab === 'proposals'" class="tab-content animate-fade-in">
        <div class="empty-state" *ngIf="myProposals.length === 0">
          <div class="icon">🤝</div>
          <p>You haven't submitted any proposals yet.</p>
          <a routerLink="/marketplace" class="btn btn-primary">Browse Marketplace</a>
        </div>
        <div class="grid-auto" *ngIf="myProposals.length > 0">
          <div class="resource-card card" *ngFor="let prop of myProposals">
            <div class="card-top">
              <span class="badge badge-success" *ngIf="prop.accepted">✅ Accepted</span>
              <span class="badge badge-warning" *ngIf="!prop.accepted">⏳ Pending</span>
            </div>
            <p class="card-desc">{{ prop.proposal }}</p>
            <div class="card-meta">
              <span>Amount: ₹{{ prop.amount | number }}</span>
              <span>{{ prop.proposalDate | date }}</span>
            </div>
            <div class="card-actions">
              <button class="btn btn-danger btn-sm"
                      (click)="deleteProposal(prop.propId!)" [id]="'btn-del-prop-' + prop.propId">
                🗑️ Withdraw
              </button>
            </div>
          </div>
        </div>
      </div>
    </ng-container>
  </div>
</div>

// marketplace-react/src/components/Dashboard/Dashboard.jsx
import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { getEmployeeRequirements, getEmployeeOffers, getAllProposals, updateRequirementFulfilled, updateOfferAvailability, deleteRequirement, deleteOffer, deleteProposal } from '../../services/api';
import { ClipboardList, PackageOpen, Handshake, Plus, Trash2, Edit2, CheckCircle, XCircle } from 'lucide-react';
import Spinner from '../shared/Spinner';
import Badge from '../shared/Badge';
import EmptyState from '../shared/EmptyState';
import styles from './Dashboard.module.css';

const Dashboard = () => {
  const { state } = useAuth();
  const empId = state.employee?.empId;

  const [activeTab, setActiveTab] = useState('requirements');
  const [loading, setLoading] = useState(true);
  
  const [requirements, setRequirements] = useState([]);
  const [offers, setOffers] = useState([]);
  const [proposals, setProposals] = useState([]);

  const loadData = useCallback(async () => {
    if (!empId) {
      setLoading(false);
      return;
    }
    setLoading(true);
    try {
      const [reqsRes, offersRes, propsRes] = await Promise.all([
        getEmployeeRequirements(empId),
        getEmployeeOffers(empId),
        getAllProposals()
      ]);
      setRequirements(reqsRes.data);
      setOffers(offersRes.data);
      setProposals(propsRes.data.filter(p => p.emp?.empId === empId));
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [empId]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  // Actions
  const handleMarkFulfilled = async (req) => {
    try {
      const res = await updateRequirementFulfilled(req);
      setRequirements(requirements.map(r => r.resId === res.data.resId ? res.data : r));
    } catch (err) { console.error(err); }
  };

  const handleMarkUnavailable = async (offer) => {
    try {
      const updated = { ...offer, available: false };
      const res = await updateOfferAvailability(updated);
      setOffers(offers.map(o => o.resId === res.data.resId ? res.data : o));
    } catch (err) { console.error(err); }
  };

  const handleDeleteReq = async (id) => {
    if (!window.confirm('Delete this requirement?')) return;
    try {
      await deleteRequirement(id);
      setRequirements(requirements.filter(r => r.resId !== id));
    } catch (err) { console.error(err); }
  };

  const handleDeleteOffer = async (id) => {
    if (!window.confirm('Delete this offer?')) return;
    try {
      await deleteOffer(id);
      setOffers(offers.filter(o => o.resId !== id));
    } catch (err) { console.error(err); }
  };

  const handleDeleteProp = async (id) => {
    if (!window.confirm('Delete this proposal?')) return;
    try {
      await deleteProposal(id);
      setProposals(proposals.filter(p => p.propId !== id));
    } catch (err) { console.error(err); }
  };

  if (!empId) {
    return <div className="page-content"><div className="container"><EmptyState icon="⚠️" message="Employee profile not found." /></div></div>;
  }

  return (
    <div className="page-content">
      <div className="container">
        
        {/* Header */}
        <div className={`section-header animate-fade-in ${styles.header}`}>
          <div>
            <h1 className={styles.title}>My Dashboard</h1>
            <p className="text-muted">Manage your requirements, offers and proposals</p>
          </div>
          <div className={styles.actions}>
            <Link to="/requirements/new" className="btn btn-primary">
              <Plus size={16} /> New Requirement
            </Link>
            <Link to="/offers/new" className="btn btn-accent">
              <Plus size={16} /> New Offer
            </Link>
          </div>
        </div>

        {loading ? (
          <Spinner />
        ) : (
          <div className="animate-slide-up">
            {/* Stats Row */}
            <div className={styles.statsRow}>
              <div 
                className={`card ${styles.statCard} ${activeTab === 'requirements' ? styles.active : ''}`}
                onClick={() => setActiveTab('requirements')}
              >
                <ClipboardList className={styles.statIcon} size={28} color="var(--primary-light)" />
                <div className={styles.statCount}>{requirements.length}</div>
                <div className={styles.statLabel}>Requirements</div>
              </div>

              <div 
                className={`card ${styles.statCard} ${activeTab === 'offers' ? styles.active : ''}`}
                onClick={() => setActiveTab('offers')}
              >
                <PackageOpen className={styles.statIcon} size={28} color="var(--accent)" />
                <div className={styles.statCount}>{offers.length}</div>
                <div className={styles.statLabel}>Offers</div>
              </div>

              <div 
                className={`card ${styles.statCard} ${activeTab === 'proposals' ? styles.active : ''}`}
                onClick={() => setActiveTab('proposals')}
              >
                <Handshake className={styles.statIcon} size={28} color="var(--success)" />
                <div className={styles.statCount}>{proposals.length}</div>
                <div className={styles.statLabel}>My Proposals</div>
              </div>
            </div>

            {/* Tab Content */}
            <div className={styles.tabContent}>
              {activeTab === 'requirements' && (
                <>
                  {requirements.length === 0 ? (
                    <EmptyState icon={<ClipboardList size={48} />} message="No requirements yet. Post your first requirement!" />
                  ) : (
                    <div className="grid-auto animate-fade-in">
                      {requirements.map(req => (
                        <div key={req.resId} className="card flex-col justify-between">
                          <div>
                            <div className="flex gap-2 mb-4">
                              <Badge variant="primary">{req.category}</Badge>
                              {req.fulfilled 
                                ? <Badge variant="success">Fulfilled</Badge>
                                : <Badge variant="warning">Open</Badge>
                              }
                            </div>
                            <h3 className="mb-4">{req.title}</h3>
                            <p className="text-muted text-sm mb-4 line-clamp-2">{req.description}</p>
                          </div>
                          
                          <div className={styles.cardActions}>
                            {!req.fulfilled && (
                              <button className="btn btn-success btn-sm" onClick={() => handleMarkFulfilled(req)}>
                                <CheckCircle size={14} /> Fulfill
                              </button>
                            )}
                            <Link to={`/requirements/${req.resId}/edit`} className="btn btn-outline btn-sm">
                              <Edit2 size={14} /> Edit
                            </Link>
                            <button className="btn btn-danger btn-sm" onClick={() => handleDeleteReq(req.resId)}>
                              <Trash2 size={14} />
                            </button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </>
              )}

              {activeTab === 'offers' && (
                <>
                  {offers.length === 0 ? (
                    <EmptyState icon={<PackageOpen size={48} />} message="No offers yet. Post your first offer!" />
                  ) : (
                    <div className="grid-auto animate-fade-in">
                      {offers.map(offer => (
                        <div key={offer.resId} className="card flex-col justify-between">
                          <div>
                            <div className="flex gap-2 mb-4">
                              <Badge variant="primary">{offer.category}</Badge>
                              {offer.available 
                                ? <Badge variant="success">Available</Badge>
                                : <Badge variant="danger">Unavailable</Badge>
                              }
                            </div>
                            <h3 className="mb-4">{offer.title}</h3>
                            <p className="text-muted text-sm mb-4 line-clamp-2">{offer.description}</p>
                          </div>
                          
                          <div className={styles.cardActions}>
                            {offer.available && (
                              <button className="btn btn-outline btn-sm" onClick={() => handleMarkUnavailable(offer)}>
                                <XCircle size={14} /> Mark Unavailable
                              </button>
                            )}
                            <Link to={`/offers/${offer.resId}/edit`} className="btn btn-outline btn-sm">
                              <Edit2 size={14} /> Edit
                            </Link>
                            <button className="btn btn-danger btn-sm" onClick={() => handleDeleteOffer(offer.resId)}>
                              <Trash2 size={14} />
                            </button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </>
              )}

              {activeTab === 'proposals' && (
                <>
                  {proposals.length === 0 ? (
                    <EmptyState icon={<Handshake size={48} />} message="You haven't submitted any proposals yet." />
                  ) : (
                    <div className="grid-auto animate-fade-in">
                      {proposals.map(prop => (
                        <div key={prop.propId} className="card flex-col justify-between">
                          <div>
                            <div className="flex gap-2 mb-4">
                              {prop.accepted 
                                ? <Badge variant="success">Accepted</Badge>
                                : <Badge variant="warning">Pending</Badge>
                              }
                            </div>
                            <p className="mb-4">"{prop.proposal}"</p>
                            <div className="text-sm text-secondary mb-4">
                              <div>Amount: ₹{prop.amount.toLocaleString()}</div>
                              <div>Date: {new Date(prop.proposalDate).toLocaleDateString()}</div>
                            </div>
                          </div>
                          <div className={styles.cardActions}>
                            <button className="btn btn-danger btn-sm" onClick={() => handleDeleteProp(prop.propId)}>
                              <Trash2 size={14} /> Withdraw
                            </button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Dashboard;
