// marketplace-frontend/src/app/components/marketplace/marketplace.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { Requirement, Offer } from '../../models/models';

@Component({
  selector: 'app-marketplace',
  templateUrl: './marketplace.component.html',
  styleUrls: ['./marketplace.component.css']
})
export class MarketplaceComponent implements OnInit {
  requirements: Requirement[] = [];
  offers: Offer[] = [];
  loading = true;
  activeView: 'requirements' | 'offers' | 'all' = 'all';
  filterCategory = '';
  filterType = '';
  searchTerm = '';

  categories = ['Accommodation', 'Electronics', 'Vehicle', 'Services', 'Other'];
  types = ['SELL', 'RENT', 'FREE', 'HELP'];

  get isLoggedIn() { return this.auth.isLoggedIn; }

  constructor(private api: ApiService, public auth: AuthService) {}

  ngOnInit(): void {
    this.loadAll();
  }

  loadAll(): void {
    this.loading = true;
    const category = this.filterCategory || undefined;
    const type = this.filterType || undefined;

    this.api.getAllRequirements(category, type).subscribe({
      next: (r) => { this.requirements = r; this.checkDone(); },
      error: () => this.checkDone()
    });
    this.api.getAllOffers(category, type).subscribe({
      next: (o) => { this.offers = o; this.checkDone(); },
      error: () => this.checkDone()
    });
  }

  private loaded = 0;
  checkDone(): void {
    this.loaded++;
    if (this.loaded >= 2) { this.loading = false; this.loaded = 0; }
  }

  applyFilters(): void {
    this.loadAll();
  }

  clearFilters(): void {
    this.filterCategory = '';
    this.filterType = '';
    this.searchTerm = '';
    this.loadAll();
  }

  get filteredRequirements(): Requirement[] {
    if (!this.searchTerm) return this.requirements;
    const t = this.searchTerm.toLowerCase();
    return this.requirements.filter(r =>
      r.title?.toLowerCase().includes(t) || r.description?.toLowerCase().includes(t)
    );
  }

  get filteredOffers(): Offer[] {
    if (!this.searchTerm) return this.offers;
    const t = this.searchTerm.toLowerCase();
    return this.offers.filter(o =>
      o.title?.toLowerCase().includes(t) || o.description?.toLowerCase().includes(t)
    );
  }
}

<div class="page-content">
  <div class="container">
    <!-- Hero -->
    <div class="page-hero animate-fade-in">
      <h1>🏪 Marketplace</h1>
      <p>Find what you need or offer what you have — within your company</p>
    </div>

    <!-- Filters -->
    <div class="filters-panel card animate-fade-in">
      <div class="filters-row">
        <div class="search-wrapper">
          <span class="search-icon">🔍</span>
          <input
            id="market-search"
            type="text"
            class="form-control"
            placeholder="Search requirements and offers..."
            [(ngModel)]="searchTerm"
          />
        </div>

        <select id="filter-category" class="form-control filter-select" [(ngModel)]="filterCategory">
          <option value="">All Categories</option>
          <option *ngFor="let cat of categories" [value]="cat">{{ cat }}</option>
        </select>

        <select id="filter-type" class="form-control filter-select" [(ngModel)]="filterType">
          <option value="">All Types</option>
          <option *ngFor="let t of types" [value]="t">{{ t }}</option>
        </select>

        <button id="btn-apply-filter" class="btn btn-primary" (click)="applyFilters()">Filter</button>
        <button id="btn-clear-filter" class="btn btn-outline" (click)="clearFilters()">Clear</button>
      </div>

      <!-- View toggle -->
      <div class="view-toggle">
        <button [class.active]="activeView === 'all'" (click)="activeView = 'all'" id="view-all">All</button>
        <button [class.active]="activeView === 'requirements'" (click)="activeView = 'requirements'" id="view-req">
          📋 Requirements ({{ filteredRequirements.length }})
        </button>
        <button [class.active]="activeView === 'offers'" (click)="activeView = 'offers'" id="view-offers">
          📦 Offers ({{ filteredOffers.length }})
        </button>
      </div>
    </div>

    <div *ngIf="loading" class="spinner"></div>

    <ng-container *ngIf="!loading">
      <!-- Requirements section -->
      <div *ngIf="activeView === 'all' || activeView === 'requirements'">
        <div class="section-header">
          <h2 class="section-title">📋 Requirements</h2>
          <a routerLink="/requirements/new" class="btn btn-primary btn-sm" *ngIf="isLoggedIn"
             id="btn-post-req">+ Post Requirement</a>
        </div>

        <div class="empty-state" *ngIf="filteredRequirements.length === 0">
          <div class="icon">📋</div>
          <p>No requirements found matching your filters.</p>
        </div>

        <div class="grid-auto animate-fade-in" *ngIf="filteredRequirements.length > 0">
          <div class="resource-card card" *ngFor="let req of filteredRequirements">
            <div class="card-top-row">
              <span class="badge badge-primary">{{ req.category }}</span>
              <span class="badge badge-warning">{{ req.type }}</span>
              <span class="badge badge-success" *ngIf="req.fulfilled">Fulfilled</span>
            </div>
            <h3 class="res-title">{{ req.title }}</h3>
            <p class="res-desc text-muted">{{ req.description }}</p>
            <div class="res-footer">
              <div class="res-meta">
                <span class="res-price" *ngIf="req.price">₹{{ req.price | number }}</span>
                <span class="res-who">by {{ req.emp?.empName }}</span>
              </div>
              <a [routerLink]="['/requirements', req.resId]" class="btn btn-outline btn-sm"
                 [id]="'btn-view-req-' + req.resId">View →</a>
            </div>
          </div>
        </div>
      </div>

      <div class="divider" *ngIf="activeView === 'all'"></div>

      <!-- Offers section -->
      <div *ngIf="activeView === 'all' || activeView === 'offers'">
        <div class="section-header">
          <h2 class="section-title">📦 Offers</h2>
          <a routerLink="/offers/new" class="btn btn-accent btn-sm" *ngIf="isLoggedIn"
             id="btn-post-offer">+ Post Offer</a>
        </div>

        <div class="empty-state" *ngIf="filteredOffers.length === 0">
          <div class="icon">📦</div>
          <p>No offers found matching your filters.</p>
        </div>

        <div class="grid-auto animate-fade-in" *ngIf="filteredOffers.length > 0">
          <div class="resource-card card offer-card" *ngFor="let offer of filteredOffers">
            <div class="card-top-row">
              <span class="badge badge-primary">{{ offer.category }}</span>
              <span class="badge badge-warning">{{ offer.type }}</span>
              <span class="badge badge-success" *ngIf="offer.available">Available</span>
              <span class="badge badge-danger" *ngIf="!offer.available">Unavailable</span>
            </div>
            <h3 class="res-title">{{ offer.title }}</h3>
            <p class="res-desc text-muted">{{ offer.description }}</p>
            <div class="res-footer">
              <div class="res-meta">
                <span class="res-price" *ngIf="offer.price">₹{{ offer.price | number }}</span>
                <span class="res-who">by {{ offer.emp?.empName }}</span>
              </div>
              <a [routerLink]="['/offers', offer.resId]" class="btn btn-outline btn-sm"
                 [id]="'btn-view-offer-' + offer.resId">View →</a>
            </div>
          </div>
        </div>
      </div>
    </ng-container>
  </div>
</div>

// marketplace-react/src/components/Marketplace/Marketplace.jsx
import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { getAllResources } from '../../services/api';
import { Search, Plus, Filter, RefreshCcw } from 'lucide-react';
import Spinner from '../shared/Spinner';
import Badge from '../shared/Badge';
import EmptyState from '../shared/EmptyState';
import styles from './Marketplace.module.css';

const CATEGORIES = ['Accommodation', 'Electronics', 'Vehicle', 'Services', 'Other'];
const TYPES = ['SELL', 'RENT', 'FREE', 'HELP'];

const Marketplace = ({ defaultView = 'all' }) => {
  const { state } = useAuth();
  const [resources, setResources] = useState([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [searchTerm, setSearchTerm] = useState('');
  const [filterCategory, setFilterCategory] = useState('');
  const [filterType, setFilterType] = useState('');
  const [activeView, setActiveView] = useState(defaultView);

  const fetchResources = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getAllResources({
        category: filterCategory || undefined,
        type: filterType || undefined
      });
      setResources(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [filterCategory, filterType]);

  useEffect(() => {
    setActiveView(defaultView);
  }, [defaultView]);

  useEffect(() => {
    fetchResources();
  }, [fetchResources]);

  const clearFilters = () => {
    setSearchTerm('');
    setFilterCategory('');
    setFilterType('');
  };

  // Derived state
  const reqs = resources.filter(r => r.resourceType === 'REQUIREMENT');
  const offers = resources.filter(r => r.resourceType === 'OFFER');

  const filterBySearch = (list) => {
    if (!searchTerm) return list;
    const term = searchTerm.toLowerCase();
    return list.filter(r => 
      r.title.toLowerCase().includes(term) || 
      (r.description && r.description.toLowerCase().includes(term))
    );
  };

  const displayReqs = filterBySearch(reqs);
  const displayOffers = filterBySearch(offers);

  return (
    <div className="page-content">
      <div className="container">
        
        {/* Hero */}
        <div className="page-hero animate-fade-in">
          <h1>🏪 Marketplace</h1>
          <p>Find what you need or offer what you have — within your company</p>
        </div>

        {/* Filters Panel */}
        <div className={`card ${styles.filtersPanel} animate-slide-up`}>
          <div className={styles.filtersRow}>
            <div className={styles.searchWrapper}>
              <Search className={styles.searchIcon} size={18} />
              <input
                type="text"
                className="form-control"
                placeholder="Search requirements and offers..."
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
              />
            </div>

            <select className="form-control" value={filterCategory} onChange={e => setFilterCategory(e.target.value)}>
              <option value="">All Categories</option>
              {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
            </select>

            <select className="form-control" value={filterType} onChange={e => setFilterType(e.target.value)}>
              <option value="">All Types</option>
              {TYPES.map(t => <option key={t} value={t}>{t}</option>)}
            </select>

            <button className="btn btn-outline" onClick={clearFilters} title="Clear Filters">
              <RefreshCcw size={16} />
            </button>
          </div>

          <div className={styles.viewToggle}>
            <button className={activeView === 'all' ? styles.active : ''} onClick={() => setActiveView('all')}>
              All
            </button>
            <button className={activeView === 'requirements' ? styles.active : ''} onClick={() => setActiveView('requirements')}>
              📋 Requirements ({displayReqs.length})
            </button>
            <button className={activeView === 'offers' ? styles.active : ''} onClick={() => setActiveView('offers')}>
              📦 Offers ({displayOffers.length})
            </button>
          </div>
        </div>

        {loading ? (
          <Spinner />
        ) : (
          <div className={styles.contentArea}>
            
            {/* Requirements Section */}
            {(activeView === 'all' || activeView === 'requirements') && (
              <div className="animate-fade-in">
                <div className="section-header">
                  <h2 className="section-title">📋 Requirements</h2>
                  {state.isLoggedIn && (
                    <Link to="/requirements/new" className="btn btn-primary btn-sm">
                      <Plus size={16} /> Post Requirement
                    </Link>
                  )}
                </div>

                {displayReqs.length === 0 ? (
                  <EmptyState icon="📋" message="No requirements found matching your filters." />
                ) : (
                  <div className="grid-auto">
                    {displayReqs.map(req => (
                      <div key={req.resId} className={`card ${styles.resourceCard}`}>
                        <div className={styles.cardTop}>
                          <Badge variant="primary">{req.category}</Badge>
                          <Badge variant="warning">{req.type}</Badge>
                          {req.fulfilled && <Badge variant="success">Fulfilled</Badge>}
                        </div>
                        <h3 className={styles.title}>{req.title}</h3>
                        <p className={`text-muted ${styles.desc}`}>{req.description}</p>
                        <div className={styles.cardFooter}>
                          <div className={styles.meta}>
                            {req.price > 0 && <span className={styles.price}>₹{req.price.toLocaleString()}</span>}
                            <span className={styles.author}>by {req.emp?.empName}</span>
                          </div>
                          <Link to={`/requirements/${req.resId}`} className="btn btn-outline btn-sm">
                            View →
                          </Link>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}

            {activeView === 'all' && <div className="divider" />}

            {/* Offers Section */}
            {(activeView === 'all' || activeView === 'offers') && (
              <div className="animate-fade-in" style={{ animationDelay: '0.1s' }}>
                <div className="section-header">
                  <h2 className="section-title">📦 Offers</h2>
                  {state.isLoggedIn && (
                    <Link to="/offers/new" className="btn btn-accent btn-sm">
                      <Plus size={16} /> Post Offer
                    </Link>
                  )}
                </div>

                {displayOffers.length === 0 ? (
                  <EmptyState icon="📦" message="No offers found matching your filters." />
                ) : (
                  <div className="grid-auto">
                    {displayOffers.map(offer => (
                      <div key={offer.resId} className={`card ${styles.resourceCard} ${styles.offerCard}`}>
                        <div className={styles.cardTop}>
                          <Badge variant="primary">{offer.category}</Badge>
                          <Badge variant="warning">{offer.type}</Badge>
                          {offer.available 
                            ? <Badge variant="success">Available</Badge>
                            : <Badge variant="danger">Unavailable</Badge>
                          }
                        </div>
                        <h3 className={styles.title}>{offer.title}</h3>
                        <p className={`text-muted ${styles.desc}`}>{offer.description}</p>
                        <div className={styles.cardFooter}>
                          <div className={styles.meta}>
                            {offer.price > 0 && <span className={styles.price}>₹{offer.price.toLocaleString()}</span>}
                            <span className={styles.author}>by {offer.emp?.empName}</span>
                          </div>
                          <Link to={`/offers/${offer.resId}`} className="btn btn-outline btn-sm">
                            View →
                          </Link>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}

          </div>
        )}
      </div>
    </div>
  );
};

export default Marketplace;
