// marketplace-react/src/components/OfferForm/OfferForm.jsx
import { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { getOffer, addOffer, updateOffer } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { ArrowLeft, Save } from 'lucide-react';
import Spinner from '../shared/Spinner';

const CATEGORIES = ['Accommodation', 'Electronics', 'Vehicle', 'Services', 'Other'];
const TYPES = ['SELL', 'RENT', 'FREE', 'HELP'];

const OfferForm = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { state } = useAuth();
  
  const isEdit = !!id;
  const [loading, setLoading] = useState(isEdit);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    category: '',
    type: '',
    price: '',
    availableUpto: ''
  });

  const fetchOfferData = useCallback(async () => {
    try {
      const res = await getOffer(id);
      const offer = res.data;
      if (offer.emp?.empId !== state.employee?.empId) {
        navigate('/dashboard'); // Not owner
        return;
      }
      setFormData({
        title: offer.title || '',
        description: offer.description || '',
        category: offer.category || '',
        type: offer.type || '',
        price: offer.price || '',
        availableUpto: offer.availableUpto ? new Date(offer.availableUpto).toISOString().split('T')[0] : ''
      });
    } catch (err) {
      console.error(err);
      setError('Failed to load offer.');
    } finally {
      setLoading(false);
    }
  }, [id, navigate, state.employee?.empId]);

  useEffect(() => {
    if (isEdit) fetchOfferData();
  }, [isEdit, fetchOfferData]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    setError('');

    const payload = {
      ...formData,
      price: formData.price ? Number(formData.price) : 0,
      emp: { empId: state.employee.empId }
    };

    if (!payload.availableUpto) delete payload.availableUpto;

    try {
      if (isEdit) {
        await updateOffer({ ...payload, resId: Number(id) });
      } else {
        await addOffer({ ...payload, date: new Date().toISOString().split('T')[0] });
      }
      navigate('/dashboard');
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to save offer.');
      setSubmitting(false);
    }
  };

  return (
    <div className="page-content">
      <div className="container" style={{ maxWidth: '700px' }}>
        
        <div className="mb-6 animate-fade-in">
          <Link to="/dashboard" className="back-link">
            <ArrowLeft size={16} /> Back
          </Link>
          <h1 className="text-2xl mb-2">{isEdit ? '✏️ Edit Offer' : '🚀 Post an Offer'}</h1>
          <p className="text-secondary">
            {isEdit ? 'Update your offer details' : 'Tell others what you have to offer'}
          </p>
        </div>

        {loading ? (
          <Spinner />
        ) : (
          <div className="card animate-slide-up">
            {error && <div className="alert alert-danger">{error}</div>}

            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label className="form-label" htmlFor="title">Title *</label>
                <input 
                  id="title" name="title" type="text" className="form-control"
                  placeholder="e.g. Selling iPhone 13, Mint Condition"
                  value={formData.title} onChange={handleChange} required 
                />
              </div>

              <div className="form-group">
                <label className="form-label" htmlFor="description">Description</label>
                <textarea 
                  id="description" name="description" className="form-control" rows="4"
                  placeholder="Provide more details about the offer..."
                  value={formData.description} onChange={handleChange} 
                />
              </div>

              <div className="grid-2">
                <div className="form-group">
                  <label className="form-label" htmlFor="category">Category *</label>
                  <select id="category" name="category" className="form-control" 
                          value={formData.category} onChange={handleChange} required>
                    <option value="">Select category</option>
                    {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label" htmlFor="type">Type</label>
                  <select id="type" name="type" className="form-control" 
                          value={formData.type} onChange={handleChange}>
                    <option value="">Select type</option>
                    {TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                  </select>
                </div>
              </div>

              <div className="grid-2">
                <div className="form-group">
                  <label className="form-label" htmlFor="price">Price (₹)</label>
                  <input 
                    id="price" name="price" type="number" className="form-control"
                    placeholder="0 for free or negotiable" min="0"
                    value={formData.price} onChange={handleChange} 
                  />
                </div>
                <div className="form-group">
                  <label className="form-label" htmlFor="availableUpto">Available Until (Optional)</label>
                  <input 
                    id="availableUpto" name="availableUpto" type="date" className="form-control"
                    value={formData.availableUpto} onChange={handleChange} 
                  />
                </div>
              </div>

              <div className="flex gap-4 mt-8">
                <button type="submit" className="btn btn-accent flex-1 justify-center" disabled={submitting}>
                  {submitting ? 'Saving...' : <><Save size={16} /> {isEdit ? 'Update Offer' : 'Post Offer'}</>}
                </button>
                <Link to="/dashboard" className="btn btn-outline flex-1 justify-center text-center">
                  Cancel
                </Link>
              </div>
            </form>
          </div>
        )}
      </div>
    </div>
  );
};

export default OfferForm;

// marketplace-frontend/src/app/components/offer-form/offer-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { Offer } from '../../models/models';

@Component({
  selector: 'app-offer-form',
  templateUrl: './offer-form.component.html',
  styleUrls: ['./offer-form.component.css']
})
export class OfferFormComponent implements OnInit {
  isEdit = false;
  offerId?: number;
  loading = false;
  submitting = false;
  errorMsg = '';

  title = '';
  description = '';
  category = '';
  type = '';
  price = 0;
  availableUpto = '';

  categories = ['Accommodation', 'Electronics', 'Vehicle', 'Services', 'Other'];
  types = ['SELL', 'RENT', 'FREE', 'HELP'];

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private api: ApiService,
    private auth: AuthService
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id && id !== 'new') {
      this.isEdit = true;
      this.offerId = Number(id);
      this.loading = true;
      this.api.getOffer(this.offerId).subscribe({
        next: (offer) => {
          this.title = offer.title;
          this.description = offer.description || '';
          this.category = offer.category || '';
          this.type = offer.type || '';
          this.price = offer.price || 0;
          this.availableUpto = offer.availableUpto || '';
          this.loading = false;
        },
        error: () => this.router.navigate(['/offers'])
      });
    }
  }

  onSubmit(): void {
    if (!this.title || !this.category) {
      this.errorMsg = 'Title and category are required.';
      return;
    }
    this.submitting = true;
    this.errorMsg = '';

    const emp = this.auth.currentEmployee!;
    const offer: Offer = {
      resId: this.offerId,
      title: this.title,
      description: this.description,
      category: this.category,
      type: this.type,
      price: this.price,
      available: true,
      availableUpto: this.availableUpto || undefined,
      emp
    };

    const call = this.isEdit ? this.api.updateOffer(offer) : this.api.addOffer(offer);
    call.subscribe({
      next: () => {
        this.submitting = false;
        this.router.navigate(['/dashboard']);
      },
      error: (err) => {
        this.submitting = false;
        this.errorMsg = err?.error?.message || 'Failed to save offer.';
      }
    });
  }
}

<div class="page-content">
  <div class="container">
    <div class="form-page animate-fade-in">
      <div class="form-header">
        <a routerLink="/dashboard" class="back-link">← Back</a>
        <h1>{{ isEdit ? '✏️ Edit Offer' : '📦 Post an Offer' }}</h1>
        <p class="text-muted">{{ isEdit ? 'Update your offer details' : 'Share what you have to offer' }}</p>
      </div>

      <div *ngIf="loading" class="spinner"></div>

      <div class="card form-card" *ngIf="!loading">
        <div class="alert alert-danger" *ngIf="errorMsg">⚠️ {{ errorMsg }}</div>

        <form (ngSubmit)="onSubmit()" id="offer-form">
          <div class="form-group">
            <label class="form-label" for="offer-title">Title *</label>
            <input id="offer-title" type="text" class="form-control"
                   placeholder="e.g. iPhone 14 Pro for sale"
                   [(ngModel)]="title" name="title" required />
          </div>

          <div class="form-group">
            <label class="form-label" for="offer-desc">Description</label>
            <textarea id="offer-desc" class="form-control" rows="4"
                      placeholder="Describe your offer in detail..."
                      [(ngModel)]="description" name="description"></textarea>
          </div>

          <div class="grid-2">
            <div class="form-group">
              <label class="form-label" for="offer-category">Category *</label>
              <select id="offer-category" class="form-control" [(ngModel)]="category" name="category" required>
                <option value="">Select category</option>
                <option *ngFor="let cat of categories" [value]="cat">{{ cat }}</option>
              </select>
            </div>
            <div class="form-group">
              <label class="form-label" for="offer-type">Type</label>
              <select id="offer-type" class="form-control" [(ngModel)]="type" name="type">
                <option value="">Select type</option>
                <option *ngFor="let t of types" [value]="t">{{ t }}</option>
              </select>
            </div>
          </div>

          <div class="grid-2">
            <div class="form-group">
              <label class="form-label" for="offer-price">Price (₹)</label>
              <input id="offer-price" type="number" class="form-control"
                     placeholder="0 for free" [(ngModel)]="price" name="price" min="0" />
            </div>
            <div class="form-group">
              <label class="form-label" for="offer-available-upto">Available Until</label>
              <input id="offer-available-upto" type="date" class="form-control"
                     [(ngModel)]="availableUpto" name="availableUpto" />
            </div>
          </div>

          <div class="form-actions">
            <a routerLink="/dashboard" class="btn btn-outline">Cancel</a>
            <button id="offer-submit" type="submit" class="btn btn-accent" [disabled]="submitting">
              <span *ngIf="submitting">⏳ Saving...</span>
              <span *ngIf="!submitting && !isEdit">📦 Post Offer</span>
              <span *ngIf="!submitting && isEdit">✅ Update Offer</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
